In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('used_car_train_20200313.csv')

In [8]:
data.head()

  SaleID name regDate model brand bodyType fuelType gearbox power kilometer notRepairedDamage regionCode seller offerType creatDate price v_0 v_1 v_2 v_3 v_4 v_5 v_6 v_7 v_8 v_9 v_10 v_11 v_12 v_13 v_14
0  0 736 20040402 30.0 6 1.0 0.0 0.0 60 12.5 0.0 ...
1  1 2262 20030301 40.0 1 2.0 0.0 0.0 0 15.0 - 43...
2  2 14874 20040403 115.0 15 1.0 0.0 0.0 163 12.5...
3  3 71865 19960908 109.0 10 0.0 0.0 1.0 193 15.0...
4  4 111080 20120103 110.0 5 1.0 0.0 0.0 68 5.0 0...

In [7]:
pd.set_option('display.max_columns', 50)

In [10]:
data.head(3)

  SaleID name regDate model brand bodyType fuelType gearbox power kilometer notRepairedDamage regionCode seller offerType creatDate price v_0 v_1 v_2 v_3 v_4 v_5 v_6 v_7 v_8 v_9 v_10 v_11 v_12 v_13 v_14
0  0 736 20040402 30.0 6 1.0 0.0 0.0 60 12.5 0.0 ...
1  1 2262 20030301 40.0 1 2.0 0.0 0.0 0 15.0 - 43...
2  2 14874 20040403 115.0 15 1.0 0.0 0.0 163 12.5...

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                    Non-Null Count   Dtype
---  ------                                                                                                                                                                                                    --------------   -----
 0   SaleID name regDate model brand bodyType fuelType gearbox power kilometer notRepairedDamage regionCode seller offerType creatDate price v_0 v_1 v_2 v_3 v_4 v_5 v_6 v_7 v_8 v_9 v_10 v_11 v_12 v_13 v_14  150000 non-null  object
dtypes: object(1)
memory usage: 1.1+ MB

In [13]:
data.tail(3)

       SaleID name regDate model brand bodyType fuelType gearbox power kilometer notRepairedDamage regionCode seller offerType creatDate price v_0 v_1 v_2 v_3 v_4 v_5 v_6 v_7 v_8 v_9 v_10 v_11 v_12 v_13 v_14
149997  149997 147587 20101003 60.0 11 1.0 1.0 0.0 90 ...
149998  149998 45907 20060312 34.0 10 3.0 1.0 0.0 156 ...
149999  149999 177672 19990204 19.0 28 6.0 0.0 1.0 193...

In [16]:
data.describe()

       SaleID name regDate model brand bodyType fuelType gearbox power kilometer notRepairedDamage regionCode seller offerType creatDate price v_0 v_1 v_2 v_3 v_4 v_5 v_6 v_7 v_8 v_9 v_10 v_11 v_12 v_13 v_14
count                                              150000
unique                                             150000
top     0 736 20040402 30.0 6 1.0 0.0 0.0 60 12.5 0.0 ...
freq                                                    1